posts/urls.py
from django.urls import path

from .views import (
    CommentDeleteView,
    PostDeleteView,
    PostUpdateView,
    post_comment_create_and_list_view,
    switch_like,
)

app_name = "posts"

urlpatterns = [
    path("", post_comment_create_and_list_view, name="main-post-view"),
    path("like/", switch_like, name="switch-like-view"),
    path("<pk>/delete/", PostDeleteView.as_view(), name="post-delete"),
    path("<pk>/update/", PostUpdateView.as_view(), name="post-update"),
    path("comments/<pk>/delete/", CommentDeleteView.as_view(), name="comment-delete"),
]

profiles/urls.py
from django.urls import path

from .views import (
    ChatMessageView,
    MessengerListView,
    ProfileDetailView,
    ProfileListView,
    accept_invitation,
    my_friends_view,
    my_profile_view,
    received_invites_view,
    reject_invitation,
    remove_friend,
    search_profiles,
    send_invitation,
    sent_invites_view,
    switch_follow,
)

app_name = "profiles"

urlpatterns = [
    path("", ProfileListView.as_view(), name="all-profiles-view"),
    path("users/<slug>/", ProfileDetailView.as_view(), name="profile-detail-view"),
    path("messenger/", MessengerListView.as_view(), name="messenger-list-view"),
    path("chat/<slug>/", ChatMessageView.as_view(), name="chat-message-view"),
    path("myprofile/", my_profile_view, name="my-profile-view"),
    path("search/", search_profiles, name="search-profiles-view"),
    path("my_friends/", my_friends_view, name="my-friends-view"),
    path("received_invites/", received_invites_view, name="received-invites-view"),
    path("sent_invites/", sent_invites_view, name="sent-invites-view"),
    path("switch_follow/", switch_follow, name="switch-follow-view"),
    path("send-invite/", send_invitation, name="send-invite"),
    path("remove-friend/", remove_friend, name="remove-friend"),
    path("received_invites/accept/", accept_invitation, name="accept-invite"),
    path("received_invites/reject/", reject_invitation, name="reject-invite"),
]

profiles/models.py
from django.contrib.auth.models import User
from django.core.validators import FileExtensionValidator
from django.db import models
from django.shortcuts import reverse

from .models_utils import get_likes_received_count, get_list_of_profiles_by_user


# Profile Model


class ProfileManager(models.Manager):
    def get_my_friends_profiles(self, user):
        users = Profile.objects.get(user=user).friends.all()
        profiles = get_list_of_profiles_by_user(users)
        return profiles


class Profile(models.Model):
    """
    This model gets created automatically everytime a new user sign ups
    """

    first_name = models.CharField(max_length=200, blank=True)
    last_name = models.CharField(max_length=200, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(default="No Bio..", max_length=300, blank=True)
    email = models.EmailField(max_length=200, blank=True)
    country = models.CharField(max_length=200, blank=True)
    avatar = models.ImageField(
        default="avatar.png",
        upload_to="avatars/",
        validators=[FileExtensionValidator(["png", "jpg", "jpeg"])],
    )
    friends = models.ManyToManyField(User, blank=True, related_name="friends")
    following = models.ManyToManyField(
        User,
        blank=True,
        related_name="following",
    )
    followers = models.ManyToManyField(
        User,
        blank=True,
        related_name="followers",
    )
    slug = models.SlugField(unique=True, blank=True)

    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    objects = ProfileManager()

    def __str__(self):
        return f"{self.user.username}"

    def get_absolute_url(self):
        return reverse(
            "profiles:profile-detail-view",
            kwargs={"slug": self.slug},
        )

    def save(self, *args, **kwargs):
        self.slug = str(self.user)
        super().save(*args, **kwargs)

    # Methods for profile details #

    def get_likes_given_count(self):
        # Like model is connected to Profile model via a foreign key,
        # likes given are stored in that Profile model
        likes = self.like_set.all()

        total_liked = likes.count()

        return total_liked

    def get_likes_received_count(self):
        posts = self.posts.all()

        total_liked = get_likes_received_count(posts)

        return total_liked

    ###############################


# Relationship Model


class RelationshipManager(models.Manager):
    def invitations_received(self, receiver):
        qs = Relationship.objects.filter(receiver=receiver, status="sent")
        return qs

    def invitations_sent(self, sender):
        qs = Relationship.objects.filter(sender=sender, status="sent")
        return qs


STATUS_CHOICES = (
    ("sent", "sent"),
    ("accepted", "accepted"),
)


class Relationship(models.Model):
    """
    This model is used to send/receive friend requests
    """

    sender = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="sender")
    receiver = models.ForeignKey(
        Profile,
        on_delete=models.CASCADE,
        related_name="receiver",
    )
    status = models.CharField(max_length=8, choices=STATUS_CHOICES)

    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    objects = RelationshipManager()

    def __str__(self):
        return f"{self.sender} - {self.receiver} - {self.status}"


# Message Model


class Message(models.Model):
    """
    This model is used in chat for messages (obviously)
    """

    sender = models.ForeignKey(
        Profile,
        on_delete=models.CASCADE,
        related_name="message_sender",
    )
    receiver = models.ForeignKey(
        Profile,
        on_delete=models.CASCADE,
        related_name="message_receiver",
    )
    content = models.TextField(max_length=200)

    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        if len(str(self.content)) > 50:
            return f"{self.sender} - {str(self.content)[:50].strip()}.."
        return f"{self.sender} - {str(self.content)}"

profiles/forms.py
from django import forms

from .models import Message, Profile


class ProfileModelForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ("first_name", "last_name", "bio", "avatar")


class MessageModelForm(forms.ModelForm):
    content = forms.CharField(
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Send a message.."}),
    )

    class Meta:
        model = Message
        fields = ("content",)

profiles/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import DetailView, ListView

from posts.forms import CommentCreateModelForm
from posts.models import Post
from posts.views_utils import add_comment_if_submitted

from .forms import MessageModelForm
from .models import Message, Profile, Relationship
from .views_utils import (
    check_if_friends,
    follow_unfollow,
    get_friends_of_user,
    get_profile_by_pk,
    get_profile_form_by_request_method,
    get_received_invites,
    get_received_messages,
    get_relationship_users,
    get_request_user_profile,
    get_sent_invites,
    redirect_back,
)


# Function-based views


@login_required
def my_profile_view(request):
    """
    Shows request's user profile.
    View url: /profiles/myprofile/
    """
    profile = get_request_user_profile(request.user)

    form = get_profile_form_by_request_method(request, profile)

    posts = profile.posts.all()

    c_form = CommentCreateModelForm()

    if add_comment_if_submitted(request, profile):
        return redirect_back(request)

    if request.method == "POST" and form.is_valid():
        form.save()

        messages.add_message(
            request,
            messages.SUCCESS,
            "Profile updated successfully!",
        )

        return redirect_back(request)

    context = {
        "profile": profile,
        "form": form,
        "posts": posts,
        "c_form": c_form,
    }

    return render(request, "profiles/my_profile.html", context)


@login_required
def received_invites_view(request):
    """
    Shows request's user received invites.
    View url: /profiles/received_invites/
    """
    profile = get_request_user_profile(request.user)
    profiles = get_received_invites(profile)

    context = {
        "profiles": profiles,
    }

    return render(request, "profiles/received_invites.html", context)


@login_required
def sent_invites_view(request):
    """
    Shows request's user sent invites.
    View url: /profiles/sent_invites/
    """
    profile = get_request_user_profile(request.user)
    profiles = get_sent_invites(profile)

    context = {
        "profiles": profiles,
    }

    return render(request, "profiles/sent_invites.html", context)


@login_required
def switch_follow(request):
    """
    Follows/unfollows user by pk.
    View url: /profiles/switch_follow/
    """
    if request.method == "POST":
        my_profile = get_request_user_profile(request.user)
        profile = get_profile_by_pk(request)

        follow_unfollow(my_profile, profile)

    return redirect_back(request)


@login_required
def accept_invitation(request):
    """
    Accepts invitation from user by pk.
    View url: /profiles/received_invites/accept/
    """
    if request.method == "POST":
        sender = get_profile_by_pk(request)
        receiver = get_request_user_profile(request.user)

        rel = get_object_or_404(Relationship, sender=sender, receiver=receiver)

        if rel.status == "sent":
            rel.status = "accepted"
            rel.save()

    return redirect_back(request)


@login_required
def reject_invitation(request):
    """
    Rejects (deletes) invitation from user by pk.
    View url: /profiles/received_invites/reject/
    """
    if request.method == "POST":
        sender = get_profile_by_pk(request)
        receiver = get_request_user_profile(request.user)

        rel = get_object_or_404(Relationship, sender=sender, receiver=receiver)

        if rel.status == "sent":
            rel.delete()

    return redirect_back(request)


@login_required
def my_friends_view(request):
    """
    Shows request's user friends.
    View url: /profiles/my_friends/
    """
    profile = get_request_user_profile(request.user)
    following = profile.following.all()

    profiles = Profile.objects.get_my_friends_profiles(request.user)

    context = {
        "following": following,
        "profiles": profiles,
    }

    return render(request, "profiles/my_friends.html", context)


@login_required
def search_profiles(request):
    """
    Searches for profiles by their username.
    View url: /profiles/search/
    """
    search = request.GET.get("q", "")
    profiles = Profile.objects.filter(user__username__icontains=search)

    context = {
        "search": search,
        "profiles": profiles,
    }

    if search:
        return render(request, "profiles/search_profiles.html", context)

    return render(request, "profiles/search_profiles.html")


@login_required
def send_invitation(request):
    """
    Creates a "sent" relationship between request's profile
    and target profile.
    View url: /profiles/send-invite/
    """
    if request.method == "POST":
        sender = get_request_user_profile(request.user)
        receiver = get_profile_by_pk(request)

        Relationship.objects.create(
            sender=sender,
            receiver=receiver,
            status="sent",
        )

    return redirect_back(request)


@login_required
def remove_friend(request):
    """
    Deletes relationship between request's profile and target profile.
    View url: /profiles/remove-friend/
    """
    if request.method == "POST":
        sender = get_request_user_profile(request.user)
        receiver = get_profile_by_pk(request)

        # Find relationship
        # where sender is request's profile and receiver is target profile
        # or where sender is target profile and receiver is request's profile,
        # then delete it
        rel = Relationship.objects.get(
            (Q(sender=sender) & Q(receiver=receiver))
            | (Q(sender=receiver) & Q(receiver=sender)),
        )
        rel.delete()

    return redirect_back(request)


# Class-based views


class ProfileDetailView(LoginRequiredMixin, DetailView):
    """
    Shows target profile and it's details.
    View url: /profiles/users/<slug>/
    """

    model = Profile
    template_name = "profiles/profile_detail.html"
    form_class = CommentCreateModelForm

    def get(self, request, *args, **kwargs):

        # Redirect to profiles/myprofile/
        # if request's user == target user
        if Profile.objects.get(user=self.request.user) == self.get_object():
            return redirect("profiles:my-profile-view")

        # Default BaseDetailView.get parameters
        # (this has to be here)
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):

        # Add comment form
        form = self.form_class(request.POST)

        if form.is_valid():
            instance = form.save(commit=False)
            instance.profile = get_request_user_profile(self.request.user)
            instance.post = Post.objects.get(id=request.POST.get("post_id"))
            instance.save()

            form = CommentCreateModelForm()

            return redirect_back(self.request)

    def get_object(self):
        slug = self.kwargs.get("slug")
        profile = Profile.objects.get(slug=slug)
        return profile

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        profile = get_request_user_profile(self.request.user)
        following = profile.following.all

        invited_users, incoming_invite_users = get_relationship_users(profile)

        context["invited_users"] = invited_users
        context["incoming_invite_users"] = incoming_invite_users
        context["following"] = following
        context["form"] = self.form_class

        context["profile"] = self.get_object()
        context["request_user_profile"] = profile

        context["posts"] = self.get_object().posts.all()

        return context


class ProfileListView(LoginRequiredMixin, ListView):
    """
    Shows list of all profiles except request's user.
    View url: /profiles/
    """

    model = Profile
    template_name = "profiles/profile_list.html"

    def get_queryset(self):
        qs = Profile.objects.all()
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        profile = Profile.objects.get(user=self.request.user)
        following = profile.following.all

        invited_users, incoming_invite_users = get_relationship_users(profile)

        context["invited_users"] = invited_users
        context["incoming_invite_users"] = incoming_invite_users
        context["following"] = following
        context["profiles"] = self.get_queryset()

        return context


class MessengerListView(LoginRequiredMixin, ListView):
    """
    Shows list of all profiles except request's user.
    View url: /profiles/messenger/
    """

    model = Profile
    template_name = "profiles/messenger.html"

    def get_queryset(self):
        qs = get_friends_of_user(self.request.user)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["profiles"] = self.get_queryset()

        return context


class ChatMessageView(LoginRequiredMixin, ListView):
    """
    Shows messages between request's user and target user.
    View url: /profiles/chat/<slug>/
    """

    model = Message
    template_name = "profiles/chat.html"
    form_class = MessageModelForm

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)

        if form.is_valid():
            instance = form.save(commit=False)
            instance.sender = Profile.objects.get(user=self.request.user)
            instance.receiver = self.get_object()
            instance.save()

        return redirect_back(self.request)

    def get_object(self):
        slug = self.kwargs.get("slug")

profiles/templates/profiles/profile_detail.html
{% extends 'base.html' %}
{% block title %}
    {{ profile.user }}
{% endblock title %}
{% block content %}
    {% for message in messages %}
        {% if message.tags == 'error' %}
            <div class="ui red message">
                <div class="header">Error</div>
                <p>{{ message }}</p>
            </div>
        {% else %}
            <div class="ui green message">
                <div class="header">Success</div>
                <p>{{ message }}</p>
            </div>
        {% endif %}
    {% endfor %}
    <div class='ui grid'>
        <br>
        <div class='row'>
            <div class='four wide column'>
                <img class='ui medium rounded image' src='{{ profile.avatar.url }}'>
                <h1>{{ profile.user }}</h1>
                <div class='ui vertical fluid menu'>
                    <div class='item'>
                        Posts
                        <div class='ui label'>{{ profile.posts.all.count }}</div>
                    </div>
                    <div class='item'>
                        Likes Given
                        <div class='ui label'>{{ profile.get_likes_given_count }}</div>
                    </div>
                    <div class='item'>
                        Likes Received
                        <div class='ui label'>{{ profile.get_likes_received_count }}</div>
                    </div>
                    <div class='item'>
                        Friends
                        <div class='ui label'>{{ profile.friends.all.count }}</div>
                    </div>
                    <div class='item'>
                        Followers
                        <div class='ui label'>{{ profile.followers.all.count }}</div>
                    </div>
                </div>
                <div>
                    <!-- Relationship Options (add friend, remove etc.)-->
                    <!-- Add Friend -->
                    <!-- If request user didn't send invite and pk user didn't send invite and request's user not in target user friends -->
                    {% if profile.user not in invited_users and profile.user not in incoming_invite_users and request.user not in profile.friends.all %}
                        <form action='{% url 'profiles:send-invite' %}' method='POST'>
                            {% csrf_token %}
                            <input type='hidden' name='pk' value='{{ profile.pk }}'>
                            <button style="margin-top:10px;
                                           width:200px"
                                    type='submit'
                                    class='ui positive basic button mb-5 w-big'>
                                <i class='plus square icon'></i>
                                Add Friend
                            </button>
                        </form>
                    {% endif %}
                    <!-- Waiting for approval -->
                    <!-- If request user sent invite -->
                    {% if profile.user in invited_users %}
                        <div>
                            <button style="margin-top:10px;
                                           width:200px"
                                    class='ui disabled button mb-5 w-big'>
                                <i class='user icon'></i>
                                Waiting for approval
                            </button>
                        </div>
                    {% endif %}
                    <!-- Accept Invite -->
                    <!-- If target user sent invite to request.user and request's user didn't send invite -->
                    {% if profile.user in incoming_invite_users and profile.user not in invited_users %}
                        <form action='{% url 'profiles:accept-invite' %}' method='POST'>
                            {% csrf_token %}
                            <input type='hidden' name='pk' value='{{ profile.pk }}'>
                            <button style="margin-top:10px;
                                           width:200px"
                                    type='submit'
                                    class='ui positive basic button mb-5 w-big'>
                                <i class='plus square icon'></i>
                                Accept Invite
                            </button>
                        </form>
                    {% endif %}
                    <!-- Remove Friend -->
                    <!-- If request user in target user friends -->
                    {% if request.user in profile.friends.all %}
                        <form action='{% url 'profiles:remove-friend' %}' method='POST'>
                            {% csrf_token %}
                            <input type='hidden' name='pk' value='{{ profile.pk }}'>
                            <button style="margin-top:10px;
                                           width:200px"
                                    type='submit'
                                    class='ui negative basic button mb-5 w-big'>
                                <i class='minus square icon'></i>
                                Remove Friend
                            </button>
                        </form>
                    {% endif %}
                    <!-- Follow -->
                    {% if profile.user not in following %}
                        <form action='{% url "profiles:switch-follow-view" %}' method='POST'>
                            {% csrf_token %}
                            <input type='hidden' name='pk' value='{{ profile.pk }}'>
                            <button style="margin-top:10px;
                                           width:200px"
                                    type='submit'
                                    class='ui positive basic button mb-5 w-big'>Follow</button>
                        </form>
                        <!-- Unfollow -->
                    {% else %}
                        <form action='{% url "profiles:switch-follow-view" %}' method='POST'>
                            {% csrf_token %}
                            <input type='hidden' name='pk' value='{{ profile.pk }}'>
                            <button style="margin-top:10px;
                                           width:200px"
                                    type='submit'
                                    class='ui negative basic button mb-5 w-big'>
                                Unfollow
                            </button>
                        </form>
                    {% endif %}
                    <!-- Send a message -->
                    {% if request.user in profile.friends.all %}
                        <a href="{% url "profiles:chat-message-view" profile.slug %}">
                            <button style="margin-top:10px;
                                           width:200px"
                                    type='submit'
                                    class='ui info teal basic button mb-5 w-big'>
                                Send a Message
                            </button>
                        </a>
                    {% endif %}
                </div>
                <!-- Relationship Options end -->
            </div>
            <div class='twelve wide column'>
                {% if posts %}
                    {% for post in posts  %}
                        <div class='segment ui fluid'>
                            <div class="post-content">
                                <h3>Post #{{ forloop.revcounter }}</h3>
                                <p style="color: gray">{{ post.created|timesince }} ago</p>
                                <hr>
                            </div>
                            {% if post.image %}
                                <div class="post-image">
                                    <img class="img-src" src="{{ post.image.url }}">
                                </div>
                            {% endif %}
                            <p>{{ post.content }}</p>
                            <div style="display: flex; justify-content: right;">
                                <div class="cmt_btn {{ post.id }} ui button mb-5">
                                    <i class="comment icon"></i>
                                    <p style="display: inline-block;">{{ post.num_comments }}</p>
                                </div>
                                <form action="{% url 'posts:switch-like-view' %}"
                                      method="POST"
                                      class='like-form'
                                      id='{{ post.id }}'>
                                    {% csrf_token %}
                                    <input type="hidden" name="post_id" value={{ post.id }}>
                                    {% if request_user_profile not in post.liked.all %}
                                        <button type="submit" class="ui button black like-btn{{ post.id }}">
                                            <i class="heart icon"></i>
                                            <p style="display: inline-block;" class="like-count{{ post.id }}">{{ post.liked.all.count }}</p>
                                        </button>
                                    {% else %}
                                        <button type="submit" class="ui button negative like-btn{{ post.id }}">
                                            <i class="heart icon"></i>
                                            <p style="display: inline-block;" class="like-count{{ post.id }}">{{ post.liked.all.count }}</p>
                                        </button>
                                    {% endif %}
                                </form>
                            </div>
                            <br>
                            <div class="comment-box">
                                {% if post.comment_set.all %}
                                    {% for c in post.comment_set.all %}
                                        <div class="ui segment mb-5">
                                            <img class="ui avatar image" src={{ c.profile.avatar.url }}>
                                            <span style="color:gray">
                                                <a style="color:black" href="{{ c.profile.get_absolute_url }}">{{ c.profile }}</a> {{ c.created|timesince }} ago
                                            </span>
                                            <div style="color:black" class='mt-5'>{{ c.content }}</div>
                                            <br>
                                            {% if c.profile.user == request.user %}
                                                <form method="POST" action="{% url 'posts:comment-delete' c.pk %}">
                                                    {% csrf_token %}
                                                    <button type="submit" class="delete-cmt-btn">Delete</button>
                                                </form>
                                            {% endif %}
                                        </div>
                                    {% endfor %}
                                {% endif %}
                            </div>
                            <form action="" method="POST"class='form{{ post.id }} ui fluid form'>
                                {% csrf_token %}
                                <input type="hidden" name="post_id" value={{ post.id }}>
                                {{ form.as_p }}
                                <button type="submit"
                                        name="submit_c_form"
                                        class="ui primary button mt-5 w-full">Send</button>
                            </form>
                        {% endfor %}
                    {% else %}
                        <h1>This user hasn't posted anything yet.</h1>
                    {% endif %}
                </div>
            </div>
        </div>
    {% endblock content %}
    {% block scripts %}
        {% load static %}
        <script src="{% static 'like.js' %}"></script>
        <script src="{% static 'comments.js' %}"></script>
    {% endblock scripts %}

profiles/templates/profiles/received_invites.html
{% extends 'base.html' %}
{% block title %}
    Received Invites
{% endblock title %}
{% block content %}
    <div class="ui two top attached buttons">
        <a href="{% url 'profiles:received-invites-view' %}">
            <div class="ui button active">Received Invites</div>
        </a>
        <a href="{% url 'profiles:sent-invites-view' %}">
            <div class="ui button">Sent Invites</div>
        </a>
    </div>
    {% if not profiles %}<h1>You haven't received any invites yet.</h1>{% endif %}
    {% for profile in profiles %}
        <div class='ui segment'>
            <div class='ui grid'>
                <div class='row'>
                    <div class='three wide column'>
                        <img class='ui small circular image' src='{{ profile.avatar.url }}'>
                    </div>
                    <div class='thirteen wide column'>
                        <h3>{{ profile.user }}</h3>
                        <p>{{ profile.bio }}</p>
                        <br>
                        <a href='{{ profile.get_absolute_url }}'>
                            <button style="margin-top:10px;
                                           width:200px"
                                    class="ui primary button w-big mb-5">See Profile</button>
                        </a>
                        <form action='{% url 'profiles:accept-invite' %}' method='POST'>
                            {% csrf_token %}
                            <input type='hidden' name='pk' value='{{ profile.pk }}'>
                            <button style="margin-top:10px;
                                           width:200px"
                                    type='submit'
                                    class='ui positive basic button w-big mb-5'>
                                <i class='check icon'></i>
                                Accept Invite
                            </button>
                        </form>
                        <form action='{% url 'profiles:reject-invite' %}' method='POST'>
                            {% csrf_token %}
                            <input type='hidden' name='pk' value='{{ profile.pk }}'>
                            <button style="margin-top:10px;
                                           width:200px"
                                    type='submit'
                                    class='ui negative basic button w-big mb-5'>
                                <i class='close icon'></i>
                                Reject Invite
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock content %}