posts/urls.py
from django.urls import path

from .views import (
    CommentDeleteView,
    PostDeleteView,
    PostUpdateView,
    post_comment_create_and_list_view,
    switch_like,
)

app_name = "posts"

urlpatterns = [
    path("", post_comment_create_and_list_view, name="main-post-view"),
    path("like/", switch_like, name="switch-like-view"),
    path("<pk>/delete/", PostDeleteView.as_view(), name="post-delete"),
    path("<pk>/update/", PostUpdateView.as_view(), name="post-update"),
    path("comments/<pk>/delete/", CommentDeleteView.as_view(), name="comment-delete"),
]

profiles/urls.py
from django.urls import path

from .views import (
    ChatMessageView,
    MessengerListView,
    ProfileDetailView,
    ProfileListView,
    accept_invitation,
    my_friends_view,
    my_profile_view,
    received_invites_view,
    reject_invitation,
    remove_friend,
    search_profiles,
    send_invitation,
    sent_invites_view,
    switch_follow,
)

app_name = "profiles"

urlpatterns = [
    path("", ProfileListView.as_view(), name="all-profiles-view"),
    path("users/<slug>/", ProfileDetailView.as_view(), name="profile-detail-view"),
    path("messenger/", MessengerListView.as_view(), name="messenger-list-view"),
    path("chat/<slug>/", ChatMessageView.as_view(), name="chat-message-view"),
    path("myprofile/", my_profile_view, name="my-profile-view"),
    path("search/", search_profiles, name="search-profiles-view"),
    path("my_friends/", my_friends_view, name="my-friends-view"),
    path("received_invites/", received_invites_view, name="received-invites-view"),
    path("sent_invites/", sent_invites_view, name="sent-invites-view"),
    path("switch_follow/", switch_follow, name="switch-follow-view"),
    path("send-invite/", send_invitation, name="send-invite"),
    path("remove-friend/", remove_friend, name="remove-friend"),
    path("received_invites/accept/", accept_invitation, name="accept-invite"),
    path("received_invites/reject/", reject_invitation, name="reject-invite"),
]

templates/main/home.html
{% extends 'base.html' %}
{% block title %}
    Home
{% endblock title %}
{% block content %}
    <div class="welcome">
        <h1>Welcome to Pybook!</h1>
    </div>
    <br>
    <div class='content'>
        <p>Please use the "Login" button above to login or sign-up.</p>
    </div>
{% endblock content %}

templates/main/navbar.html
{% url 'home-view' as path_to_home %}
{% url 'account_login' as login %}
{% url 'posts:main-post-view' as path_to_posts %}
{% url 'profiles:my-profile-view' as path_to_my_profile %}
{% url 'profiles:received-invites-view' as path_to_received_invites %}
{% url 'profiles:my-friends-view' as path_to_my_friends %}
{% url 'profiles:sent-invites-view' as path_to_invites %}
{% url 'profiles:all-profiles-view' as path_to_all_profiles %}
{% url 'profiles:messenger-list-view' as path_to_messenger %}
<div class="navbar ui inverted menu nav mb-5">
    <div class="ui container">
        <a href="{{ path_to_home }}"
           class="{% if request.path == path_to_home %}active{% endif %} item">
            <h3>Pybook</h3>
        </a>
        {% if request.user.is_authenticated %}
            <a href="{{ path_to_posts }}"
               class="{% if request.path == path_to_posts %}active{% endif %} item">Board</a>
        {% endif %}
        {% if request.user.is_authenticated %}
            <a href="{{ path_to_messenger }}"
               class="{% if request.path == path_to_messenger %}active{% endif %} item">Messenger</a>
        {% endif %}
        <div class="right menu">
            {% if request.user.is_authenticated %}
                <div class="item">
                    <div class="ui floating dropdown icon button teal">
                        Friends
                        <i class="dropdown icon"></i>
                        <div class="menu">
                            <a href="{{ path_to_all_profiles }}"
                               class="{% if request.path == path_to_all_profiles %}active{% endif %} item">
                                All Profiles
                            </a>
                            <a href="{{ path_to_my_friends }}"
                               class="{% if request.path == path_to_my_friends %}active{% endif %} item">
                                My Friends
                            </a>
                            <a href="{{ path_to_received_invites }}"
                               class="{% if request.path == path_to_received_invites %}active{% endif %} item">
                                Invites &nbsp;
                                <div class="ui purple horizontal label">{{ invitations_received_count }}</div>
                            </a>
                        </div>
                    </div>
                </div>
                <!-- Search -->
                <div class="item">
                    <form action="{% url 'profiles:search-profiles-view' %}" method="GET">
                        <div class="ui action left icon input">
                            <input class="prompt"
                                   type="search"
                                   name='q'
                                   placeholder="Search for profiles">
                            <i class="search icon"></i>
                            <button type='submit' class="ui button">Search</button>
                        </div>
                    </form>
                </div>
                <!-- Search end -->
                <a href="{{ path_to_my_profile }}"
                   class="{% if request.path == path_to_my_profile %}active{% endif %} item">
                    <img src={{ profile_pic.url }} class='ui avatar image'>&nbsp;
                    {{ request.user }}
                </a>
                <a href="{% url 'account_logout' %}" class="ui item">Logout</a>
            {% else %}
                <a href="{{ login }}" class="ui item">Login</a>
            {% endif %}
        </div>
    </div>
</div>