posts/urls.py
from django.urls import path

from .views import (
    CommentDeleteView,
    PostDeleteView,
    PostUpdateView,
    post_comment_create_and_list_view,
    switch_like,
)

app_name = "posts"

urlpatterns = [
    path("", post_comment_create_and_list_view, name="main-post-view"),
    path("like/", switch_like, name="switch-like-view"),
    path("<pk>/delete/", PostDeleteView.as_view(), name="post-delete"),
    path("<pk>/update/", PostUpdateView.as_view(), name="post-update"),
    path("comments/<pk>/delete/", CommentDeleteView.as_view(), name="comment-delete"),
]

posts/models.py
from django.core.validators import FileExtensionValidator
from django.db import models

from profiles.models import Profile
from profiles.views_utils import get_request_user_profile

from .models_utils import get_related_posts_queryset


class PostManager(models.Manager):
    def get_related_posts(self, user):
        profile = get_request_user_profile(user)
        friends = profile.friends.all()
        following = profile.following.all()

        related_posts = get_related_posts_queryset(profile, friends, following)

        return related_posts


class Post(models.Model):
    """
    This model is used to show results in main.html
    """

    content = models.TextField()
    image = models.ImageField(
        blank=True,
        upload_to="posts",
        validators=[FileExtensionValidator(["png", "jpg", "jpeg"])],
    )
    liked = models.ManyToManyField(Profile, blank=True, related_name="likes")
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="posts")

    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    objects = PostManager()

    def __str__(self):
        if len(str(self.content)) > 50:
            return f"{self.author} - {str(self.content)[:50].strip()}.."
        return f"{self.author} - {str(self.content)}"

    def num_comments(self):
        return self.comment_set.all().count()

    class Meta:
        ordering = ("-created",)


class Comment(models.Model):
    """
    This model is used in Posts for comments
    """

    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField(max_length=300)

    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.profile} - {self.content}"


class Like(models.Model):
    """
    This model is used to leave likes on Posts
    """

    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.profile} liked {self.post}"

posts/forms.py
from django import forms

from .models import Comment, Post


class PostCreateModelForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={"rows": 2}))

    class Meta:
        model = Post
        fields = ("content", "image")


class PostUpdateModelForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={"rows": 2}))

    class Meta:
        model = Post
        fields = ("content",)


class CommentCreateModelForm(forms.ModelForm):
    content = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "Add a comment.."}),
        label="",
    )

    class Meta:
        model = Comment
        fields = ("content",)

posts/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import DeleteView, UpdateView

from profiles.views_utils import get_request_user_profile, redirect_back

from .forms import CommentCreateModelForm, PostCreateModelForm, PostUpdateModelForm
from .models import Comment, Post
from .views_utils import (
    add_comment_if_submitted,
    add_post_if_submitted,
    get_post_id_and_post_obj,
    like_unlike_post,
)


# Function-based views


@login_required
def post_comment_create_and_list_view(request):
    """
    Shows request's user friends.
    View url: /posts/
    """
    qs = Post.objects.get_related_posts(user=request.user)
    profile = get_request_user_profile(request.user)

    p_form = PostCreateModelForm()
    c_form = CommentCreateModelForm()

    if add_post_if_submitted(request, profile):
        return redirect_back(request)

    if add_comment_if_submitted(request, profile):
        return redirect_back(request)

    context = {
        "qs": qs,
        "profile": profile,
        "p_form": p_form,
        "c_form": c_form,
    }

    return render(request, "posts/main.html", context)


@login_required
def switch_like(request):
    """
    Adds/removes like to a post.
    View url: /posts/like/
    """
    if request.method == "POST":
        post_id, post_obj = get_post_id_and_post_obj(request)
        profile = get_request_user_profile(request.user)

        like_added = like_unlike_post(profile, post_id, post_obj)

    # Return JSON response for AJAX script in like.js
    return JsonResponse(
        {"total_likes": post_obj.liked.count(), "like_added": like_added},
    )


# Class-based views


class PostDeleteView(LoginRequiredMixin, DeleteView):
    """
    Deletes a post by pk.
    View url: /posts/<pk>/delete/
    """

    model = Post
    template_name = "posts/confirm_delete.html"
    success_url = reverse_lazy("posts:main-post-view")

    def form_valid(self, *args, **kwargs):
        post = self.get_object()

        # If post's author user doesnt equal request's user
        if post.author.user != self.request.user:
            messages.add_message(
                self.request,
                messages.ERROR,
                "You aren't allowed to delete this post",
            )
            return HttpResponseRedirect(self.success_url)

        # Executes only if post's author user
        # and request's user are the same
        self.object.delete()

        messages.add_message(
            self.request,
            messages.SUCCESS,
            "Post deleted successfully!",
        )
        return HttpResponseRedirect(self.success_url)


class CommentDeleteView(LoginRequiredMixin, DeleteView):
    """
    Deletes a comment by pk.
    View url: /posts/comments/<pk>/delete/
    (This view is indentical to PostDeleteView)
    """

    model = Comment

    def form_valid(self, *args, **kwargs):
        comment = self.get_object()

        if comment.profile.user != self.request.user:
            messages.add_message(
                self.request,
                messages.ERROR,
                "You aren't allowed to delete this comment",
            )
            return redirect_back(self.request)

        # Delete the comment
        self.object.delete()

        messages.add_message(
            self.request,
            messages.SUCCESS,
            "Comment deleted successfully!",
        )
        return redirect_back(self.request)


class PostUpdateView(LoginRequiredMixin, UpdateView):
    """
    Updates a post by pk.
    View url: /posts/<pk>/update/
    (This view is (again) indentical to PostDeleteView)
    """

    model = Post
    form_class = PostUpdateModelForm
    template_name = "posts/update.html"
    success_url = reverse_lazy("posts:main-post-view")

    def form_valid(self, form):
        profile = get_request_user_profile(self.request.user)

        if form.instance.author != profile:
            messages.add_message(
                self.request,
                messages.ERROR,
                "You aren't allowed to update this post",
            )
            return HttpResponseRedirect(self.success_url)

        # Update the post
        self.object = form.save()

        messages.add_message(
            self.request,
            messages.SUCCESS,
            "Post updated successfully!",
        )
        return HttpResponseRedirect(self.success_url)

posts/templates/posts/confirm_delete.html
{% extends 'base.html' %}
{% block title %}
    Delete Post
{% endblock title %}
{% block content %}
    <div id="content-container" class="container p-none">
        <div class="side-p">
            <h3>Are you sure?</h3>
            <p>You're about to delete "{{ object }}". Please confirm.</p>
            <form action="" method="post">
                {% csrf_token %}
                <input class="ui button"
                       type="button"
                       value="Cancel"
                       onclick="window.history.go(-1);"/>
                <input class="ui button positive" type="submit" value="Confirm" />
            </form>
        </div>
    </div>
{% endblock content %}

posts/templates/posts/main.html
{% extends 'base.html' %}
{% block title %}
    Board
{% endblock title %}
{% block content %}
    {% for message in messages %}
        {% if message.tags == 'error' %}
            <div class="ui red message">
                <div class="header">Error</div>
                <p>{{ message }}</p>
            </div>
        {% else %}
            <div class="ui green message">
                <div class="header">Success</div>
                <p>{{ message }}</p>
            </div>
        {% endif %}
    {% endfor %}
    <div class="ui grid">
        <div class="eleven wide column">
            {% for post in qs %}
                <div class="ui fluid card">
                    <div class="content">
                        <div class="right floated meta">
                            <div class="ui grid">
                                <div class="row">
                                    {% if request.user == post.author.user %}
                                        <a href="{% url 'posts:post-update' post.pk %}">
                                            <button class="ui button bwhite-lg ">Update</button>
                                        </a>
                                        <a href="{% url 'posts:post-delete' post.pk %}">
                                            <button class="ui button bwhite-lg ">Delete</button>
                                        </a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        <img class="ui avatar image" src={{ post.author.avatar.url }}>
                        <span style="color:gray">
                            <a style="color:black" href="{{ post.author.get_absolute_url }}">{{ post.author.user }}</a>  {{ post.created|timesince }} ago
                        </span>
                    </div>
                    <div class="ui fluid image">
                        {% if post.image %}<img src={{ post.image.url }}>{% endif %}
                    </div>
                    <div class="content">
                        <p>{{ post.content }}</p>
                        <div style="display: flex; justify-content: right;">
                            <div class="cmt_btn {{ post.id }} ui button mb-5">
                                <i class="comment icon"></i>
                                <p style="display: inline-block;">{{ post.num_comments }}</p>
                            </div>
                            <form action="{% url 'posts:switch-like-view' %}"
                                  method="POST"
                                  class='like-form'
                                  id='{{ post.id }}'>
                                {% csrf_token %}
                                <input type="hidden" name="post_id" value={{ post.id }}>
                                {% if profile not in post.liked.all %}
                                    <button type="submit" class="ui button black like-btn{{ post.id }}">
                                        <i class="heart icon"></i>
                                        <p style="display: inline-block;" class="like-count{{ post.id }}">{{ post.liked.all.count }}</p>
                                    </button>
                                {% else %}
                                    <button type="submit" class="ui button negative like-btn{{ post.id }}">
                                        <i class="heart icon"></i>
                                        <p style="display: inline-block;" class="like-count{{ post.id }}">{{ post.liked.all.count }}</p>
                                    </button>
                                {% endif %}
                            </form>
                        </div>
                    </div>
                    <div class="extra content">
                        <div class="comment-box">
                            {% if post.comment_set.all %}
                                {% for c in post.comment_set.all %}
                                    <div class="ui segment mb-5">
                                        <img class="ui avatar image" src={{ c.profile.avatar.url }}>
                                        <span style="color:gray">
                                            <a style="color:black" href="{{ c.profile.get_absolute_url }}">{{ c.profile }}</a> {{ c.created|timesince }} ago
                                        </span>
                                        <div style="color:black" class='mt-5'>{{ c.content }}</div>
                                        <br>
                                        {% if c.profile.user == request.user %}
                                            <form method="POST" action="{% url 'posts:comment-delete' c.pk %}">
                                                {% csrf_token %}
                                                <button type="submit" class="delete-cmt-btn">Delete</button>
                                            </form>
                                        {% endif %}
                                    </div>
                                {% endfor %}
                            {% endif %}
                        </div>
                        <form action="" method="POST"class='form{{ post.id }} ui fluid form'>
                            {% csrf_token %}
                            <input type="hidden" name="post_id" value={{ post.id }}>
                            {{ c_form.as_p }}
                            <button type="submit"
                                    name="submit_c_form"
                                    class="ui primary button mt-5 w-full">Send</button>
                        </form>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="five wide column">
            <div class="ui segment">
                <form action="" method="POST" class='ui form' enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ p_form.as_p }}
                    <button type='submit'
                            name="submit_p_form"
                            class="ui positive button w-full mt-5">Send</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}
{% block scripts %}
    {% load static %}
    <script src="{% static 'comments.js' %}"></script>
    <script src="{% static 'like.js' %}"></script>
{% endblock scripts %}

posts/templates/posts/update.html
{% extends 'base.html' %}
{% block title %}
    Update Post
{% endblock title %}
{% block content %}
    <div class="ui segment">
        <h3>Update Post</h3>
        <form action="" method="POST" class="ui form" enctype="mutlipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="ui button"
                   type="button"
                   value="Cancel"
                   onclick="window.history.go(-1);"/>
            <button type="submit" class="ui button primary mt-5">Update</button>
        </form>
    </div>
{% endblock content %}